apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dp
  labels:
    app: redis-app
    type: redis
spec:
  template:
    metadata:
      name: redis-pod
      labels:
      app: redis-app
      type: redis
    spec:
      containers:
        - name: redis-container
          image: redis
  selector:
    matchLabels:
      type: redis
  replicas: 6

